#!/usr/bin/env bash
set -euo pipefail

touch ~/.no_auto_tmux
umask 0022

echo "=== AI Training bootstrap: $(date) ==="

# --------------------------------------------------
# -1) Capture the environment so we can recreate it 
#    in a (ssh) bash shell
# --------------------------------------------------

# === Persist session env for later SSH logins ===
SECRET_DIR="/root/.secrets"
SESSION_ENV="${SECRET_DIR}/env.current"

mkdir -p "$SECRET_DIR"
chmod 700 "$SECRET_DIR"
umask 077

# Vars to persist
VARS=(
  SSH_PUBLIC_KEY PUBLIC_KEY 
  HF_TOKEN
  WANDB_TOKEN
  GEMINI_API_KEY
  AI_TOOLKIT_PORT AI_TOOLKIT_AUTH
  HF_REPO_ID HF_REPO_TYPE HF_REMOTE_URL
  TRAINING_MODEL_MANIFEST_URL
  ENABLE_SAGE ENABLE_TRITON
)

{
  echo "# Autogenerated $(date -Is)"
  for k in "${VARS[@]}"; do
    # Only export if the variable named by $k is set
    if [[ ${!k+set} ]]; then
      v="${!k}"
      [[ -n "$v" ]] && printf 'export %s=%q\n' "$k" "$v"
    fi
  done
} > "$SESSION_ENV"

umask 0022

# Optional: non-secret summary of env vars
SUMMARY="/workspace/env.summary"
{
  echo "Generated: $(date -Is)"
  for k in "${VARS[@]}"; do
    # skip secrets AND skip unset
    [[ "$k" =~ TOKEN ]] && continue
    [[ "$k" =~ KEY ]] && continue
    [[ "$k" =~ AUTH ]] && continue
    if [[ ${!k+set} ]]; then
      printf '%-22s = %s\n' "$k" "${!k}"
    fi
  done
} > "$SUMMARY"

echo "Saved session env to $SESSION_ENV; summary at $SUMMARY"

# --------------------------------------------------
# 0) Wire up .env and helpers, create training dirs
# --------------------------------------------------

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENVIRONMENT="${ENVIRONMENT:-$SCRIPT_DIR/.env}"
HELPERS="${HELPERS:-$SCRIPT_DIR/helpers.sh}"

if [[ ! -f "$ENVIRONMENT" ]]; then
  echo "[fatal] Environment file not found at: $ENVIRONMENT" >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$ENVIRONMENT"

if [[ ! -f "$HELPERS" ]]; then
  echo "[fatal] helpers.sh not found at: $HELPERS" >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$HELPERS"

ensure_training_dirs

#------------------------------------------------------------------------
section 1 "Preparing Session Logging"
#----------------------------------------------
# Create startup log
#----------------------------------------------

STARTUP_LOG="${TRAINING_LOGS}/startup.log"

# Duplicate all further stdout/stderr to both Vast log and a file
exec > >(tee -a "$STARTUP_LOG") 2>&1

echo "[bootstrap] Logging to: ${STARTUP_LOG}"

#------------------------------------------------------------------------
section 2 "Vast AI Training Bootstrap Configuration"
#----------------------------------------------
# Pretty banner
#----------------------------------------------

on_start_training_banner

#------------------------------------------------------------------------
section 3 "SSH"
#----------------------------------------------
# Configure SSH using SSH* environment 
#   variables
#----------------------------------------------

setup_ssh

#------------------------------------------------------------------------
section 4 "Clone training repo"
#----------------------------------------------
# Clone or update training repo
#----------------------------------------------

clone_or_update_repo "${TRAINING_REPO_URL}" "${TRAINING_REPO_DIR}"

#------------------------------------------------------------------------
section 5 "Configure environment for TRAINING_RUNMODE=${TRAINING_RUNMODE}"
#----------------------------------------------
# Switch based on TRAINING_RUNMODE
#----------------------------------------------

tlog "TRAINING_RUNMODE=${TRAINING_RUNMODE}"

case "${TRAINING_RUNMODE}" in
  MUSUBI)
    tlog "Configuring venv for generic MUSUBI trainer..."
    use_venv
    run_musubi_cli_mode "$@"
    ;;

  MUSUBI-GUI)
    tlog "Configuring venv for Musubi WAN 2.2 GUI..."
    use_venv
    run_musubi_gui_mode "$@"
    ;;

  AI-TOOLKIT)
    tlog "Configuring venv for AI-Toolkit..."
    use_venv
    run_ai_toolkit_mode "$@"
    ;;

  DIFFUSION-PIPE)
    tlog "Configuring conda env for Diffusion Pipe..."
    use_conda_env
    run_diffusion_pipe_mode "$@"
    ;;

  *)
    die "Unknown TRAINING_RUNMODE='${TRAINING_RUNMODE}'. Expected one of: MUSUBI, MUSUBI-GUI, AI-TOOLKIT, DIFFUSION-PIPE"
    ;;
esac