#!/usr/bin/env bash
set -euo pipefail

touch ~/.no_auto_tmux
umask 0022

echo "=== AI Training bootstrap: $(date) ==="

# --------------------------------------------------
# 0) Capture the environment so we can recreate it 
#    in a bash shell
# --------------------------------------------------

ensure_workspace

# === Persist session env for later SSH logins ===
SECRET_DIR="/root/.secrets"
SESSION_ENV="${SECRET_DIR}/env.current"

mkdir -p "$SECRET_DIR"
chmod 700 "$SECRET_DIR"
umask 077

# Vars to persist
VARS=(
  SSH_PUBLIC_KEY PUBLIC_KEY 
  HF_TOKEN
  WANDB_TOKEN AI_TOOLKIT_AUTH
  HF_REPO_ID HF_REPO_TYPE HF_REMOTE_URL
  MODEL_MANIFEST_URL
)

{
  echo "# Autogenerated $(date -Is)"
  for k in "${VARS[@]}"; do
    # Only export if the variable named by $k is set
    if [[ ${!k+set} ]]; then
      v="${!k}"
      [[ -n "$v" ]] && printf 'export %s=%q\n' "$k" "$v"
    fi
  done
} > "$SESSION_ENV"

umask 0022

# Optional: non-secret summary for logs
mkdir -p /workspace/logs
SUMMARY="/workspace/logs/env.summary"
{
  echo "Generated: $(date -Is)"
  for k in "${VARS[@]}"; do
    # skip secrets AND skip unset
    [[ "$k" =~ TOKEN ]] && continue
    if [[ ${!k+set} ]]; then
      printf '%-22s = %s\n' "$k" "${!k}"
    fi
  done
} > "$SUMMARY"

echo "Saved session env to $SESSION_ENV; summary at $SUMMARY"

#------------------------------------------------------------------------
section 0 "Prepare Session Logging"
#----------------------------------------------
# 0) Create startup log
#----------------------------------------------

STARTUP_LOG="${TRAINING_LOGS}/startup.log"

# Duplicate all further stdout/stderr to both Vast log and a file
exec > >(tee -a "$STARTUP_LOG") 2>&1

echo "[bootstrap] Logging to: ${STARTUP_LOG}"

# --------------------------------------------------
# 1) Wire up .env and helpers
# --------------------------------------------------

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENVIRONMENT="${ENVIRONMENT:-$SCRIPT_DIR/.env}"
HELPERS="${HELPERS:-$SCRIPT_DIR/helpers.sh}"

if [[ ! -f "$ENVIRONMENT" ]]; then
  echo "[fatal] Environment file not found at: $ENVIRONMENT" >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$ENVIRONMENT"

if [[ ! -f "$HELPERS" ]]; then
  echo "[fatal] helpers.sh not found at: $HELPERS" >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$HELPERS"

# --------------------------------------------------
# 1.5) Pretty boot banner for Vast / RunPod logs
# --------------------------------------------------

on_start_training_banner

#------------------------------------------------------------------------
section 2 "SSH"
#----------------------------------------------
# Configure SSH using SSH* environment 
#   variables
#----------------------------------------------

setup_ssh

#------------------------------------------------------------------------
section 3 "Clone training repo"
#----------------------------------------------
# Clone or update training repo
#----------------------------------------------

clone_or_update_repo "${TRAINING_REPO_URL}" "${TRAINING_REPO_DIR}"

#------------------------------------------------------------------------

RUNMODE="${RUNMODE:-DIFFUSION-PIPE}"
log "RUNMODE=${RUNMODE}"

#------------------------------------------------------------------------
section 4 "Configure environment for RUNMODE=${RUNMODE}"
#----------------------------------------------
# Configure SSH using SSH* environment 
#   variables
#----------------------------------------------

case "${RUNMODE}" in
  MUSUBI)
    log "Configuring venv for generic MUSUBI trainer..."
    use_venv
    run_musubi_cli_mode "$@"
    ;;

  MUSUBI-GUI)
    log "Configuring venv for Musubi WAN 2.2 GUI..."
    use_venv
    run_musubi_gui_mode "$@"
    ;;

  AI-TOOLKIT)
    log "Configuring venv for AI-Toolkit..."
    use_venv
    run_ai_toolkit_mode "$@"
    ;;

  DIFFUSION-PIPE)
    log "Configuring conda env for Diffusion Pipe..."
    use_conda_env
    run_diffusion_pipe_mode "$@"
    ;;

  *)
    die "Unknown RUNMODE='${RUNMODE}'. Expected one of: MUSUBI, MUSUBI-GUI, AI-TOOLKIT, DIFFUSION-PIPE"
    ;;
esac