#!/usr/bin/env bash
set -euo pipefail

touch ~/.no_auto_tmux
umask 0022

echo "=== ComfyUI bootstrap: $(date) ==="

#----------------------------------------------
# -2) Capture the environment so we can
#       recreate it in a bash shell
#----------------------------------------------

mkdir -p /workspace

# === Persist session env for later SSH logins ===
SECRET_DIR="/root/.secrets"
SESSION_ENV="${SECRET_DIR}/env.current"

mkdir -p "$SECRET_DIR"
chmod 700 "$SECRET_DIR"
umask 077

# Vars to persist
VARS=(
  HF_TOKEN CIVITAI_TOKEN LORAS_IDS_TO_DOWNLOAD CHECKPOINT_IDS_TO_DOWNLOAD
  HF_REPO_ID HF_REPO_TYPE HF_REMOTE_URL
  MODEL_MANIFEST_URL CUSTOM_NODES_MANIFEST_URL
  ENABLE_MODEL_MANIFEST_DOWNLOAD ENABLE_CIVITAI_DOWNLOAD ENABLE_SAGE 
  INSTALL_EXTRA_CUSTOM_NODES LAUNCH_JUPYTER
  native_480p native_720p download_wan22 download_wan22_lightning download_vae
  download_wan_animate download_detection download_optimization_loras
  wan_fun_and_sdxl_helper
)

{
  echo "# Autogenerated $(date -Is)"
  for k in "${VARS[@]}"; do
    # Only export if the variable named by $k is set
    if [[ ${!k+set} ]]; then
      v="${!k}"
      [[ -n "$v" ]] && printf 'export %s=%q\n' "$k" "$v"
    fi
  done
} > "$SESSION_ENV"

umask 0022

# Optional: non-secret summary for logs
mkdir -p /workspace/logs
SUMMARY="/workspace/logs/env.summary"
{
  echo "Generated: $(date -Is)"
  for k in "${VARS[@]}"; do
    # skip secrets AND skip unset
    [[ "$k" =~ TOKEN ]] && continue
    if [[ ${!k+set} ]]; then
      printf '%-22s = %s\n' "$k" "${!k}"
    fi
  done
} > "$SUMMARY"

echo "Saved session env to $SESSION_ENV; summary at $SUMMARY"

#----------------------------------------------
# -1) Wire up .env and helpers
#----------------------------------------------

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENVIRONMENT="${ENVIRONMENT:-$SCRIPT_DIR/.env}"
HELPERS="${HELPERS:-$SCRIPT_DIR/helpers.sh}"

if [[ ! -f "$ENVIRONMENT" ]]; then
  echo "[fatal] .env not found at: $ENVIRONMENT" >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$ENVIRONMENT"

if [[ ! -f "$HELPERS" ]]; then
  echo "[fatal] helpers.sh not found at: $HELPERS" >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$HELPERS"

# make sure dirs exist (Comfy home, models, logs, etc.)

ensure_dirs

#------------------------------------------------------------------------
section 0 "Prepare Session Logging"
#----------------------------------------------
# 0) Create startup log
#----------------------------------------------

STARTUP_LOG="${COMFY_LOGS}/startup.log"

# Duplicate all further stdout/stderr to both Vast log and a file
exec > >(tee -a "$STARTUP_LOG") 2>&1

echo "[bootstrap] Logging to: ${STARTUP_LOG}"

#------------------------------------------------------------------------
section 1 "Status/Configuration Overview"
#----------------------------------------------
# Pretty boot banner for Vast / RunPod logs
#----------------------------------------------

on_start_banner

#------------------------------------------------------------------------
section 2 "SSH"
#----------------------------------------------
# Configure SSH using SSH* environment 
#   variables
#----------------------------------------------

setup_ssh

#------------------------------------------------------------------------
section 3 "Relocate ComfyUI"
#----------------------------------------------
# Ensure ComfyUI lives on the network volume
#   /ComfyUI  →  $COMFY_HOME (/workspace/ComfyUI)
#----------------------------------------------
if [[ -d /ComfyUI ]]; then
  mkdir -p "$(dirname "$COMFY_HOME")"

  echo "[comfy-relocate] Merging base /ComfyUI into existing $COMFY_HOME structure (no overwrite)"
  # Trailing slashes are important: copy contents, not the dir itself
  rsync -a --ignore-existing /ComfyUI/ "$COMFY_HOME"/
  # Optional: once you trust it, you can remove the original to avoid confusion
  # rm -rf /ComfyUI
else
  echo "[comfy-relocate] ❌ Comfy not installed in expected location. Unable to move."
fi

#------------------------------------------------------------------------
section 4 "Move Upscalers"
#----------------------------------------------
# Move 4xLSDIR.pth into upscale_models if 
#   present
#----------------------------------------------

if [[ -f "/4xLSDIR.pth" && ! -f "$UPSCALE_DIR/4xLSDIR.pth" ]]; then
  echo "Moving 4xLSDIR.pth into $UPSCALE_DIR..."
  mv /4xLSDIR.pth "$UPSCALE_DIR/4xLSDIR.pth"
elif [[ -f "$UPSCALE_DIR/4xLSDIR.pth" ]]; then
  echo "4xLSDIR.pth already in place, skipping move."
else
  echo "4xLSDIR.pth not found; skipping."
fi

#------------------------------------------------------------------------
section 5 "Huggingface & CivitAI Download"
#----------------------------------------------
# Models via model_manifest.json + aria2
#----------------------------------------------

helpers_have_aria2_rpc || aria2_start_daemon
aria2_clear_results >/dev/null 2>&1 || true

if [[ "${ENABLE_MODEL_MANIFEST_DOWNLOAD:-1}" == "1" ]]; then
  echo "Using model manifest: $MODEL_MANIFEST_URL"
  if ! aria2_download_from_manifest; then
    echo "⚠️ aria2_download_from_manifest failed; see logs."
  fi
else
  echo "ENABLE_MODEL_MANIFEST_DOWNLOAD=0 → skipping model downloader."
fi

if [[ "${ENABLE_CIVITAI_DOWNLOAD:-1}" == "1" ]]; then
  echo "Attempting to download CivitAI assets from env IDs... "
  echo "LORAS:${LORAS_IDS_TO_DOWNLOAD}, CHECKPOINTS:${CHECKPOINT_IDS_TO_DOWNLOAD}"
  if ! aria2_download_civitai_from_environment_vars; then
    echo "⚠️ aria2_download_civitai_from_environment_vars reported issues; see CivitAI log."
  fi
else
  echo "ENABLE_CIVITAI_DOWNLOAD=0 → skipping CivitAI downloader."
fi

aria2_show_download_snapshot || true

#------------------------------------------------------------------------
section 6 "SageAttention: Pull (if available) or Build from Source"
#----------------------------------------------
# Prefer pull of SageAttention for speed. Build
#   if not.
#----------------------------------------------

if [[ "${ENABLE_SAGE:-1}" == "1" ]]; then
  echo "Ensuring SageAttention (bundle or build)..."
  if ! ensure_sage_from_bundle_or_build; then
    echo "⚠️ SageAttention failed; check logs. Continuing without aborting."
  fi
else
  echo "ENABLE_SAGE=0 → skipping SageAttention setup."
fi

aria2_show_download_snapshot || true

#------------------------------------------------------------------------
section 7 "Install Custom Nodes"
#----------------------------------------------
# Install all Custom Nodes from Manifest
#----------------------------------------------

if [[ "${INSTALL_EXTRA_CUSTOM_NODES:-1}" == "1" ]]; then
  echo "Installing custom nodes. Trying ${CUSTOM_NODES_MANIFEST_URL}..."
  if ! install_custom_nodes; then
    echo "⚠️ install_custom_nodes reported errors; custom-node extras may be incomplete."
  fi
  snapshot_custom_nodes_state "after-install_custom_nodes" || true
else
  echo "INSTALL_EXTRA_CUSTOM_NODES=0 → skipping extra custom node installation."
fi

aria2_show_download_snapshot || true

#------------------------------------------------------------------------
section 8 "Hearmeman24 Asset Copy"
#----------------------------------------------
# Optional Hearmeman workflows/assets sync
#----------------------------------------------

copy_hearmeman_assets_if_any || true

#------------------------------------------------------------------------
section 9 "Aria2 (Manifest+CivitAI) Tracking"
#----------------------------------------------
# Wait for all downloads to complete
#----------------------------------------------

echo "[aria2-downloads-progress] Checking download progress..."

aria2_monitor_progress \
  "${ARIA2_PROGRESS_INTERVAL:-15}" \
  "${ARIA2_PROGRESS_BAR_WIDTH:-40}" \
  "${COMFY_LOGS:-/workspace/logs}/aria2_progress.log"

aria2_clear_results >/dev/null 2>&1 || true

#------------------------------------------------------------------------
section 10 "Jupyter Launch"
#----------------------------------------------
# Optionally start Jupyter if requested
#----------------------------------------------

if [[ "${LAUNCH_JUPYTER:-0}" == "1" ]]; then
  echo "Launching Jupyter. Trying from port 8888..."
  jupyter-lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password='' --ServerApp.allow_origin='*' --ServerApp.allow_credentials=True --notebook-dir=/workspace &>/workspace/logs/jupyter.log &
else
  echo "LAUNCH_JUPYTER=0 → skipping Jupyter launch..."
fi

#------------------------------------------------------------------------
section 11 "Comfy Flow/Methodology Specific Configurations"
#----------------------------------------------
# Specific Hearmeman methodologies / setups
#    Copy Hearmeman's workflows to ComfyUI & 
#    configure sensible defaults
#----------------------------------------------

copy_workflows_to_comfyui || true

change_latent_preview_method || true

#------------------------------------------------------------------------
section 12 "ComfyUI Launch"
#----------------------------------------------
# Report the Custom Nodes being used for this 
#   session. Use tmux's to launch ComfyUI
#   Send telegram message if configured
#----------------------------------------------

# Final snapshot of custom_nodes before ComfyUI launch
snapshot_custom_nodes_state --summary "before-comfy-launch" || true

cd "${COMFY_HOME:-/workspace/ComfyUI}"

echo "▶️  Starting ComfyUI"

if ${SCRIPT_DIR}/run_comfy_mux.sh; then
  tg "🚀 ComfyUI is UP on 8188, 8288 (GPU0), 8388 (GPU1 if present)." || true
else
  tg "⚠️ ComfyUI launch had warnings. Check ${COMFY_LOGS}." || true
fi

echo "Bootstrap complete. Bootstrap log: ${COMFY_LOGS}/startup.log"
echo "General logs: ${COMFY_LOGS}" 

echo "=== Bootstrap done: $(date) ==="

sleep infinity