#!/usr/bin/env bash
set -euo pipefail

touch ~/.no_auto_tmux
umask 0022

echo "=== ComfyUI bootstrap: $(date) ==="

#----------------------------------------------
# -2) Capture the environment so we can
#       recreate it in a bash shell
#----------------------------------------------

# === Persist session env for later SSH logins ===
SECRET_DIR="/root/.secrets"
SESSION_ENV="${SECRET_DIR}/env.current"

mkdir -p "$SECRET_DIR"
chmod 700 "$SECRET_DIR"
umask 077

# Prefixes to persist (pattern is bash glob)
PERSIST_GLOBS=(
  "ENABLE_*"
  "INSTALL_*"
  "*_TOKEN"
  "HF_*"
  "GIT_*"
  "LAUNCH_*"
  "TELEGRAM_*"
  "*_URL"
  "*_IDS_TO_DOWNLOAD"
)

# Gather candidate variable names from the environment (NUL-separated; safe)
mapfile -d '' -t __env_names < <(env -0 | sed -z 's/=.*//')

# Filter to those matching any desired glob
__persist_names=()
for n in "${__env_names[@]}"; do
  # sanity: only normal bash identifiers
  [[ "$n" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue

  for g in "${PERSIST_GLOBS[@]}"; do
    if [[ "$n" == $g ]]; then
      __persist_names+=("$n")
      break
    fi
  done
done

# De-dupe + stable order
IFS=$'\n' __persist_names=($(printf "%s\n" "${__persist_names[@]}" | awk '!seen[$0]++' | sort))
unset IFS

# Write the secret env file
{
  echo "# Autogenerated $(date -Is)"
  for k in "${__persist_names[@]}"; do
    # Only export if set in current shell/env
    if [[ ${!k+set} ]]; then
      v="${!k}"
      [[ -n "$v" ]] && printf 'export %s=%q\n' "$k" "$v"
    fi
  done
} > "$SESSION_ENV"

umask 0022

# Optional: non-secret summary for logs
mkdir -p /workspace/logs
SUMMARY="/workspace/logs/env.summary"

# Anything matching these substrings is treated as secret-ish and omitted
SECRET_NAME_RE='(TOKEN|SECRET|PASSWORD|PASS|KEY|CREDENTIAL|COOKIE|BEARER|AUTH|PRIVATE)'

{
  echo "Generated: $(date -Is)"
  for k in "${__persist_names[@]}"; do
    [[ "$k" =~ $SECRET_NAME_RE ]] && continue
    if [[ -v "$k" ]]; then
      printf '%-32s = %s\n' "$k" "${!k}"
    fi
  done
} > "$SUMMARY"

echo "Saved session env to $SESSION_ENV; summary at $SUMMARY"

mkdir -p /workspace /workspace/logs
PROFILE_DIR=/opt/comfyui-minimax
source "${PROFILE_DIR}/src/.env.minimax"
source "${POD_RUNTIME_DIR}/helpers.sh"

#------------------------------------------------------------------------
section 0 "Prepare Session Logging"
#------------------------------------------------------------------------

STARTUP_LOG="${COMFY_LOGS}/startup-minimax.log"
exec > >(tee -a "${STARTUP_LOG}") 2>&1

echo "[bootstrap] Logging to: ${STARTUP_LOG}"

echo "=== MiniMax bootstrap: $(date -Is) ==="
echo "Application: ${COMFY_APP}"
echo "State: ${COMFY_STATE}"

#------------------------------------------------------------------------
section 0.1 "Start-up Telegram Message"
#------------------------------------------------------------------------

tg "▶️ Starting bootstrap of ComfyUI Minimax H3 inference session" || true

#------------------------------------------------------------------------
section 0.5 "Basic Housekeeping"
#------------------------------------------------------------------------

# SSH is the recovery path. It must be available before any diagnostic or bulk
# network activity so a broken probe/download cannot make the pod inaccessible.
echo "[bootstrap] Bringing up SSH recovery access before network qualification..."
setup_ssh || true

# Qualify network performance before hf-tools, custom nodes, Sage, or models.
# The guarded helper has a hard outer wall-clock ceiling and never aborts startup.
network_probe_startup_guarded || true

gpu_name="$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -n1 || true)"
compute_cap="$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -n1 || true)"
echo "GPU: ${gpu_name:-unknown}; compute capability: ${compute_cap:-unknown}"
echo "HF base families  : ${HF_BASE_DOWNLOADS:-<none>}"
echo "HF LoRA families  : ${HF_LORA_DOWNLOADS:-<none>}"
echo "Model manifest    : ${MODEL_MANIFEST_URL}"
echo "Sage available    : ${ENABLE_SAGE:-false}"
echo "Global Sage launch: ${COMFY_USE_SAGE_ATTENTION:-false}"

# Runtime Hub operations use the isolated HFF tooling venv. Do not reinstall or
# verify hf_transfer/huggingface-hub inside the ComfyUI venv: custom nodes own
# their application dependencies and bootstrap tooling must not mutate them.
install_system_hff
hf_transfer_tune

install_root_shell_dotfiles || true

ensure_comfy_dirs

link_comfy_state_into_app

#------------------------------------------------------------------------
section 3 "Git Auth Bootstrap"
#------------------------------------------------------------------------

git_auth_bootstrap || true

#------------------------------------------------------------------------
section 4 "Install Custom Nodes"
#------------------------------------------------------------------------
# Keep this phase free of bulk model downloads. Custom-node pip installs are
# latency and I/O sensitive, while the HF/Xet model phase is throughput-oriented.

# Install custom nodes before bulk model transfers. The generic resolver always
# includes the shared default set and then adds CUSTOM_NODE_SETS=minimax. A
# failed clone/install is recorded by the installer and telemetry, but it must
# not terminate PID 1 and send the whole container into a restart loop.
if [[ "${INSTALL_CUSTOM_NODES}" == true ]]; then
  node_manifest="${CUSTOM_NODES_MANIFEST_URL_OVERRIDE:-${CUSTOM_NODES_MANIFEST_URL}}"
  echo "[nodes] Installing set '${CUSTOM_NODE_SETS}' from ${node_manifest}"
  if install_custom_nodes "${node_manifest}"; then
    echo "[nodes] Custom-node install completed successfully."
  else
    echo "WARNING: One or more custom nodes failed to install; continuing bootstrap for diagnosis." >&2
    echo "WARNING: See ${COMFY_LOGS}/custom_nodes/install_status.json and per-node logs under ${COMFY_LOGS}/custom_nodes/." >&2
  fi
  snapshot_custom_nodes_state "after-custom-node-install" || true

  # A custom-node requirement can install CPU onnxruntime after the image's GPU
  # package. Reassert the baked GPU package only when provider enumeration proves
  # it was displaced. --no-deps is intentional: a repair must not upgrade numpy,
  # protobuf, or any other already-constrained application dependency.
  if python - <<'PY'
try:
    import onnxruntime as ort
    providers = ort.get_available_providers()
except Exception as exc:
    print(f"[onnxruntime] provider probe failed: {exc}")
    raise SystemExit(1)
print("[onnxruntime] providers after custom-node install:", providers)
raise SystemExit(0 if "CUDAExecutionProvider" in providers else 1)
PY
  then
    echo "[onnxruntime] CUDA provider intact; keeping baked onnxruntime-gpu installation."
  else
    echo "[onnxruntime] CUDA provider missing after custom-node install; repairing GPU runtime without dependency churn."
    "$PIP" uninstall -y onnxruntime onnxruntime-gpu >/dev/null 2>&1 || true
    "$PIP" install --constraint /opt/constraints.txt --no-deps --force-reinstall onnxruntime-gpu
  fi
fi

#------------------------------------------------------------------------
section 5 "SageAttention: Pull (if available) or Build from Source"
#------------------------------------------------------------------------

# SageAttention is an optional runtime capability, not an image dependency.
# Reuse the normal pod-runtime architecture/Torch keyed bundle cache; build and
# optionally publish a bundle only when no compatible artifact already exists.
sage_ready=false
if [[ "${ENABLE_SAGE:-true}" == "true" ]]; then
  echo "[sage] Ensuring SageAttention bundle or source build..."
  if ensure_sage_from_bundle_or_build; then
    sage_ready=true
    push_sage_bundle_if_requested || true
  else
    echo "WARNING: SageAttention setup failed; continuing with Comfy Kitchen/default attention." >&2
  fi
else
  echo "[sage] ENABLE_SAGE=false — SageAttention availability setup skipped."
fi

# Never request the global ComfyUI Sage backend if availability setup failed.
# KJ's Patch Sage Attention node remains usable whenever sage_ready=true while
# COMFY_USE_SAGE_ATTENTION=false.
if [[ "${COMFY_USE_SAGE_ATTENTION:-false}" == "true" && "${sage_ready}" != "true" ]]; then
  echo "WARNING: COMFY_USE_SAGE_ATTENTION=true but SageAttention is unavailable; disabling global Sage for this launch." >&2
  export COMFY_USE_SAGE_ATTENTION=false
fi

#------------------------------------------------------------------------
section 6 "Hugging Face Base Models"
#------------------------------------------------------------------------
# HF_BASE_DOWNLOADS is a comma/space-separated family list. Each family maps
# directly to <family>_base in model_manifest.json. Base downloads are started
# only after custom-node/Sage setup, then may overlap the lightweight workflow
# sync below.

base_download_started=false
MINIMAX_HF_STATE="${HF_MANIFEST_STATE_DIR}/base"
if [[ "${ENABLE_MODEL_MANIFEST_DOWNLOAD}" == true ]]; then
  if [[ -n "${HF_BASE_DOWNLOADS:-}" ]]; then
    base_sections="$(hf_manifest_sections_for_families "${MODEL_MANIFEST_URL}" "${HF_BASE_DOWNLOADS}" base)" || {
      echo "ERROR: Could not resolve HF_BASE_DOWNLOADS='${HF_BASE_DOWNLOADS}'." >&2
      exit 2
    }
    echo "[models] Starting manifest download: ${MODEL_MANIFEST_URL}"
    echo "[models] Base families: ${HF_BASE_DOWNLOADS}"
    echo "[models] Base sections: ${base_sections}"
    if hf_download_from_manifest "${MODEL_MANIFEST_URL}" "$MINIMAX_HF_STATE" "$base_sections"; then
      base_download_started=true
    else
      echo "WARNING: Base manifest download failed to start; see logs." >&2
    fi
  else
    echo "[models] HF_BASE_DOWNLOADS is empty; no base models requested."
  fi
else
  echo "[models] Model provisioning disabled."
fi

#------------------------------------------------------------------------
section 7 "Workflow Repository"
#------------------------------------------------------------------------
# This small setup phase is intentionally allowed to overlap the base model
# downloader once the I/O-sensitive custom-node phase has completed.
if [[ "${ENABLE_MY_WORKFLOWS_DOWNLOAD:-false}" == "true" ]]; then
  init_repo --git "$GIT_MYWORKFLOWS_REPO_ID" "$GIT_MYWORKFLOWS_REPO_LOCAL" || true
  rsync_or_symlink_source_to_destination symlink "$GIT_MYWORKFLOWS_REPO_LOCAL" "/workspace"
  _sync_info "✅ Linking files from $GIT_MYWORKFLOWS_REPO_LOCAL into ComfyUI directories via symlinks..."
  mkdir -p "$COMFY_HOME/user/default/workflows/MyWorkflows"
  ln -sfn $GIT_MYWORKFLOWS_REPO_LOCAL/* "$COMFY_HOME/user/default/workflows/MyWorkflows/"

  _sync_info "Ensuring git auth for MyWorkflows repo for future updates (pull/push)..."
  git_repo_use_deploy_key \
    "$GIT_MYWORKFLOWS_REPO_LOCAL" "$GIT_MYWORKFLOWS_REPO_KEY" "$GIT_MYWORKFLOWS_REPO_ID"
else
  echo "ENABLE_MY_WORKFLOWS_DOWNLOAD=false → skipping MyWorkflows sync."
fi

#------------------------------------------------------------------------
section 8 "Pull my model repo from Hugging Face and symlink into ComfyUI"
#------------------------------------------------------------------------

if [[ "${ENABLE_MY_REPO_DOWNLOAD:-false}" == "true" ]]; then
  export HF_EXCLUDE_GLOBS="${HF_MY_REPO_EXCLUDE_GLOBS:-training/** snapshot/** models/loras/** deleteme/** latestimages/**}"
  export HF_INCLUDE_GLOBS="${HF_MY_REPO_INCLUDE_GLOBS:-models/ultralytics/** models/upscale_models/**}"

  if HF_REPO_TYPE="${HF_MY_REPO_TYPE:-model}" \
      init_repo --hf "$HF_MY_REPO_ID" "$HF_MY_REPO_LOCAL"; then
    if ! hf_my_repo_sync_assets "$HF_MY_REPO_LOCAL" "$HF_MY_REPO_ID"; then
      _sync_warn "$HF_MY_REPO_ID downloaded, but asset extraction/linking reported errors."
    fi
  else
    _sync_warn "HF repo download failed for $HF_MY_REPO_ID at '$HF_MY_REPO_LOCAL'."
  fi
else
  echo "ENABLE_MYREPO_DOWNLOAD=false → skipping MyRepo sync."
fi

# Base models are blocking: do not advertise the pod as ready until this phase
# has finished. A failed item is reported loudly, but ComfyUI is still launched
# so the pod remains usable for diagnosis/manual recovery.

if [[ "${base_download_started}" == true ]]; then
  echo "[models] Waiting for selected base weights..."
  if hf_download_wait "$MINIMAX_HF_STATE"; then
    echo "[models] Selected base weights are ready."
  else
    echo "WARNING: One or more base model downloads failed; continuing for diagnosis." >&2
    hf_download_show_snapshot "$MINIMAX_HF_STATE" || true
  fi
fi

pod_models_summary || true

#------------------------------------------------------------------------
section 9 "ComfyUI"
#------------------------------------------------------------------------

section 9.1 "Pre-ComfyUI Launch: Confirming Stack Health"

confirm_stack_health_or_stop || true
if [[ -f "${COMFY_LOGS}/stack_broken" ]]; then
  echo "ERROR: stack health check failed; see ${COMFY_LOGS}/stack_health_report.txt" >&2
  tail -f /dev/null
fi

python - <<'PY'
import os
import onnxruntime as ort
import torch
import comfy_aimdo
import comfy_kitchen

assert torch.version.cuda and torch.version.cuda.startswith("13"), torch.version.cuda
assert torch.cuda.is_available(), "CUDA unavailable"
print("torch:", torch.__version__, "CUDA:", torch.version.cuda)
print("GPU:", torch.cuda.get_device_name(0))
print("onnxruntime providers:", ort.get_available_providers())
assert "CUDAExecutionProvider" in ort.get_available_providers()
print("comfy_aimdo:", getattr(comfy_aimdo, "__version__", "installed"))
print("comfy_kitchen:", getattr(comfy_kitchen, "__version__", "installed"))
try:
    import sageattention
    print("sageattention:", getattr(sageattention, "__version__", "installed"))
except Exception as exc:
    print("sageattention: unavailable", repr(exc))
print("COMFY_USE_SAGE_ATTENTION:", os.environ.get("COMFY_USE_SAGE_ATTENTION", "false"))
PY

section 9.2 "ComfyUI Launch..."

snapshot_custom_nodes_state --summary "before-comfyui-minimax-launch" || true

echo ""
echo "▶️  Starting ComfyUI"
echo ""

show_env || true

cd "${COMFY_APP}"
if "${POD_RUNTIME_DIR}/run_comfy_mux.sh" start; then
  echo "MiniMax ComfyUI is available on port 8188."
  tg "🚀 Minimax: ComfyUI is UP on 8188." || true
else
  echo "ERROR: ComfyUI failed to become healthy; see ${COMFY_LOGS}/comfyui-8188.log" >&2
  tg "⚠️ ComfyUI launch had warnings. Check ${COMFY_LOGS}." || true
  exit 1
fi

#------------------------------------------------------------------------
section 10 "LoRA Families (Optional)"
#------------------------------------------------------------------------

# Optional LoRA families use the same generic family resolver and start only
# after ComfyUI is healthy, so they never delay time-to-ready.
MINIMAX_LORA_HF_STATE="${HF_MANIFEST_STATE_DIR}/loras"
if [[ "${ENABLE_MODEL_MANIFEST_DOWNLOAD}" == true && -n "${HF_LORA_DOWNLOADS:-}" ]]; then
  lora_sections="$(hf_manifest_sections_for_families "${MODEL_MANIFEST_URL}" "${HF_LORA_DOWNLOADS}" loras)" || {
    echo "WARNING: Could not resolve HF_LORA_DOWNLOADS='${HF_LORA_DOWNLOADS}'; optional LoRAs will not be downloaded." >&2
    lora_sections=""
  }
  if [[ -n "$lora_sections" ]]; then
    echo "[loras] Families: ${HF_LORA_DOWNLOADS}"
    echo "[loras] Sections: ${lora_sections}"
    if hf_download_from_manifest "$MODEL_MANIFEST_URL" "$MINIMAX_LORA_HF_STATE" "$lora_sections"; then
      echo "[loras] Optional LoRA provisioning is running in the background."
      hf_download_show_snapshot "$MINIMAX_LORA_HF_STATE" || true
    else
      echo "⚠️ Optional LoRA downloader failed to start." >&2
    fi
  fi
else
  echo "[loras] No optional LoRA families requested."
fi

pod_models_summary || true

#------------------------------------------------------------------------
section 11 "Disk Watcher"
#------------------------------------------------------------------------

disk_watch_start --path / --log "${COMFY_LOGS}/disk_watch.log" || true
pod_nag --interval 3600 || true

echo ""
echo "MiniMax Bootstrap complete. Bootstrap log: ${COMFY_LOGS}/startup.log"
echo "General logs: ${COMFY_LOGS}"
echo ""
echo "=== Bootstrap done: $(date -Is) ==="

sleep infinity
