#!/usr/bin/env bash
set -euo pipefail

touch ~/.no_auto_tmux
umask 0022

install_root_shell_dotfiles() {
  local repo_root="${1:-/workspace/pod-runtime}"   # pass POD_RUNTIME_DIR if you like
  local target_home="/root"
  local ts; ts="$(date +%Y%m%d_%H%M%S)"

  mkdir -p "$target_home"

  # Backups (if files already exist)
  for f in .bashrc .bash_aliases .bash_functions; do
    if [[ -f "${target_home}/${f}" ]]; then
      cp -a "${target_home}/${f}" "${target_home}/${f}.bak.${ts}"
    fi
  done

  # Render .bashrc with precise placeholder substitution (atomic)
  local src_bashrc="${repo_root}/.bashrc"
  local tmp; tmp="$(mktemp "${target_home}/.bashrc.tmp.XXXXXX")"

  awk -v rr="$repo_root" '
    BEGIN {done=0}
    /^[[:space:]]*REPO_ROOT=<CHANGEME>[[:space:]]*$/ {
      print "REPO_ROOT=" rr
      done=1
      next
    }
    {print}
    END {
      if (!done) {
        # If you want strict mode, uncomment:
        print "ERROR: REPO_ROOT=<CHANGEME> placeholder not found" > "/dev/stderr"
        exit 2
      }
    }
  ' "$src_bashrc" > "$tmp"

  chmod 0644 "$tmp"
  mv -f "$tmp" "${target_home}/.bashrc"

  # Copy the others
  install -m 0644 "${repo_root}/.bash_aliases"   "${target_home}/.bash_aliases"
  install -m 0644 "${repo_root}/.bash_functions" "${target_home}/.bash_functions"
  install -m 0644 "${repo_root}/.bash_prompt"    "${target_home}/.bash_prompt"
  install -m 0644 "${repo_root}/.git-qol.sh"     "${target_home}/.git-qol.sh"

  echo "[dotfiles] Installed bash dotfiles into ${target_home} (repo_root=${repo_root})"
}

ensure_hf_tools_venv() {
  local venv="${HFF_VENV:-/opt/hf-tools-venv}"
  local py="${PYTHON:-python3}"

  if [[ -x "$venv/bin/python" ]]; then
    export HFF_VENV="$venv"
    return 0
  fi

  echo "[hf-tools] Creating venv: $venv"
  "$py" -m venv "$venv" || return 1

  "$venv/bin/python" -m pip install -U pip >/dev/null || return 1

  # If you want hard pins, uncomment and set versions:
  # "$venv/bin/pip" install -U "huggingface-hub==1.3.1" "hf-transfer==0.1.9" >/dev/null || return 1

  "$venv/bin/pip" install -U huggingface-hub hf-transfer >/dev/null || return 1

  export HFF_VENV="$venv"
  echo "[hf-tools] Ready: $venv"
}

install_hff_py() {
  local src="${1:-/workspace/pod-runtime}/bin/hff.py"   # pass POD_RUNTIME if you like
  local dst="/usr/local/bin/hff.py"

  if [[ ! -f "$src" ]]; then
    echo "[hf-tools] hff.py not found: $src" >&2
    return 1
  fi

  install -m 0755 "$src" "$dst"
  echo "[hf-tools] Installed: $dst"
}

hf_tools_verify() {
  local venv="${HFF_VENV:-/opt/hf-tools-venv}"
  "$venv/bin/python" - <<'PY'
import huggingface_hub, os
print("huggingface_hub:", getattr(huggingface_hub, "__version__", "?"))
print("HF_HUB_ENABLE_HF_TRANSFER:", os.environ.get("HF_HUB_ENABLE_HF_TRANSFER"))
try:
  import hf_transfer
  print("hf_transfer: OK")
except Exception as e:
  print("hf_transfer: missing:", e)
PY
  command -v "$venv/bin/huggingface-cli" >/dev/null 2>&1 && echo "huggingface-cli: OK" || echo "huggingface-cli: missing"
}

install_system_hff() {
  ensure_hf_tools_venv || return 1
  install_hff_py || return 1
  hf_tools_verify
}

echo "=== ComfyUI bootstrap: $(date) ==="

#----------------------------------------------
# -2) Capture the environment so we can
#       recreate it in a bash shell
#----------------------------------------------

mkdir -p /workspace

# === Persist session env for later SSH logins ===
SECRET_DIR="/root/.secrets"
SESSION_ENV="${SECRET_DIR}/env.current"

mkdir -p "$SECRET_DIR"
chmod 700 "$SECRET_DIR"
umask 077

# Vars to persist
VARS=(
  HF_TOKEN CIVITAI_TOKEN LORAS_IDS_TO_DOWNLOAD CHECKPOINT_IDS_TO_DOWNLOAD
  HF_REPO_ID HF_REPO_TYPE HF_REMOTE_URL
  MODEL_MANIFEST_URL CUSTOM_NODES_MANIFEST_URL
  ENABLE_MODEL_MANIFEST_DOWNLOAD ENABLE_CIVITAI_DOWNLOAD ENABLE_SAGE 
  INSTALL_CUSTOM_NODES LAUNCH_JUPYTER
  download_480p_native_models download_720p_native_models 
  download_wan22 download_wan22_lightning download_wan_animate 
  download_wan22_animate_god_mode_25 download_wan_fun_and_sdxl_helper 
  download_wan22_svi
  download_vae download_detection
  download_optimization_loras
  download_gguf
  download_aio_mega
  download_vace_artofficial
  download_qwen download_qwen_image_edit
  download_upscale
)

{
  echo "# Autogenerated $(date -Is)"
  for k in "${VARS[@]}"; do
    # Only export if the variable named by $k is set
    if [[ ${!k+set} ]]; then
      v="${!k}"
      [[ -n "$v" ]] && printf 'export %s=%q\n' "$k" "$v"
    fi
  done
} > "$SESSION_ENV"

umask 0022

# Optional: non-secret summary for logs
mkdir -p /workspace/logs
SUMMARY="/workspace/logs/env.summary"
{
  echo "Generated: $(date -Is)"
  for k in "${VARS[@]}"; do
    # skip secrets AND skip unset
    [[ "$k" =~ TOKEN ]] && continue
    if [[ ${!k+set} ]]; then
      printf '%-22s = %s\n' "$k" "${!k}"
    fi
  done
} > "$SUMMARY"

echo "Saved session env to $SESSION_ENV; summary at $SUMMARY"

#----------------------------------------------
# -1) Wire up .env and helpers
#----------------------------------------------

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENVIRONMENT="${ENVIRONMENT:-$SCRIPT_DIR/.env}"
HELPERS="${HELPERS:-$SCRIPT_DIR/helpers.sh}"

if [[ ! -f "$ENVIRONMENT" ]]; then
  echo "[fatal] .env not found at: $ENVIRONMENT" >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$ENVIRONMENT"

if [[ ! -f "$HELPERS" ]]; then
  echo "[fatal] helpers.sh not found at: $HELPERS" >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$HELPERS"

# Install hf-tools into system

install_system_hff || {
  echo "[fatal] hf-tools installation failed." >&2
  exit 1
}

# Move dotfiles into root home for other SSH connections

install_root_shell_dotfiles || true

# make sure dirs exist (Comfy home, models, logs, etc.)

ensure_comfy_dirs

#------------------------------------------------------------------------
section 0 "Prepare Session Logging"
#----------------------------------------------
# 0) Create startup log
#----------------------------------------------

STARTUP_LOG="${COMFY_LOGS}/startup.log"

# Duplicate all further stdout/stderr to both Vast log and a file
exec > >(tee -a "$STARTUP_LOG") 2>&1

echo "[bootstrap] Logging to: ${STARTUP_LOG}"

#------------------------------------------------------------------------
section 0.5 "Basic Housekeeping"
#----------------------------------------------

#----------------------------------------------
# Install fast HF backend (safe, quiet) into ComfyUI venv
#----------------------------------------------

# Map helper knobs into hf_transfer / hub vars
hf_transfer_tune

# Install / verify hf download backend
hf_transfer_install
hf_transfer_verify

#------------------------------------------------------------------------
section 1 "Status/Configuration Overview"
#----------------------------------------------
# Pretty boot banner for Vast / RunPod logs
#----------------------------------------------

on_start_comfy_banner

#------------------------------------------------------------------------
section 2 "SSH"
#----------------------------------------------
# Configure SSH using SSH* environment 
#   variables
#----------------------------------------------

setup_ssh

#------------------------------------------------------------------------
section 3 "Relocate ComfyUI"
#----------------------------------------------
# Ensure ComfyUI lives on the network volume
#   /ComfyUI  →  $COMFY_HOME (/workspace/ComfyUI)
#----------------------------------------------
if [[ -d /ComfyUI ]]; then
  mkdir -p "$(dirname "$COMFY_HOME")"

  echo "[comfy-relocate] Merging base /ComfyUI into existing $COMFY_HOME structure (no overwrite)"
  # Trailing slashes are important: copy contents, not the dir itself
  rsync -a --ignore-existing /ComfyUI/ "$COMFY_HOME"/
  # Optional: once you trust it, you can remove the original to avoid confusion
  # rm -rf /ComfyUI
else
  echo "[comfy-relocate] ❌ Comfy not installed in expected location. Unable to move."
fi

#------------------------------------------------------------------------
section 4 "Move Upscalers"
#----------------------------------------------
# Move 4xLSDIR.pth into upscale_models if 
#   present
#----------------------------------------------

if [[ -f "/4xLSDIR.pth" && ! -f "$UPSCALE_DIR/4xLSDIR.pth" ]]; then
  echo "Moving 4xLSDIR.pth into $UPSCALE_DIR..."
  mv /4xLSDIR.pth "$UPSCALE_DIR/4xLSDIR.pth"
elif [[ -f "$UPSCALE_DIR/4xLSDIR.pth" ]]; then
  echo "4xLSDIR.pth already in place, skipping move."
else
  echo "4xLSDIR.pth not found; skipping."
fi

#------------------------------------------------------------------------
section 5 "Huggingface (Models) & CivitAI (Loras/Checkpoints) Download"
#----------------------------------------------
# Models via model_manifest.json + aria2
#----------------------------------------------

helpers_have_aria2_rpc || aria2_start_daemon
aria2_clear_results >/dev/null 2>&1 || true

if [[ "${ENABLE_MODEL_MANIFEST_DOWNLOAD:-true}" == "true" ]]; then
  echo "Using model manifest: $MODEL_MANIFEST_URL"
  if ! aria2_download_from_manifest; then
    echo "⚠️ aria2_download_from_manifest failed; see logs."
  fi
else
  echo "ENABLE_MODEL_MANIFEST_DOWNLOAD=false → skipping model downloader."
fi

if [[ "${ENABLE_CIVITAI_DOWNLOAD:-true}" == "true" ]]; then
  echo "Attempting to download CivitAI assets from env IDs... "
  echo "LORAS:${LORAS_IDS_TO_DOWNLOAD}, CHECKPOINTS:${CHECKPOINT_IDS_TO_DOWNLOAD}"
  if ! aria2_download_civitai_from_environment_vars; then
    echo "⚠️ aria2_download_civitai_from_environment_vars reported issues; see CivitAI log."
  fi
else
  echo "ENABLE_CIVITAI_DOWNLOAD=false → skipping CivitAI downloader."
fi

aria2_show_download_snapshot || true

#------------------------------------------------------------------------
section 6 "SageAttention: Pull (if available) or Build from Source"
#----------------------------------------------
# Prefer pull of SageAttention for speed. Build
#   if not.
#----------------------------------------------

if [[ "${ENABLE_SAGE:-true}" == "true" ]]; then
  echo "Ensuring SageAttention (bundle or build)..."
  if ! ensure_sage_from_bundle_or_build; then
    echo "⚠️ SageAttention failed; check logs. Continuing without aborting."
  fi
else
  echo "ENABLE_SAGE=false → skipping SageAttention setup."
fi

aria2_show_download_snapshot || true

#------------------------------------------------------------------------
section 7 "Install Custom Nodes"
#----------------------------------------------
# Install all Custom Nodes from Manifest
#----------------------------------------------

if [[ "${INSTALL_CUSTOM_NODES:-true}" == "true" ]]; then
  echo "Installing custom nodes. Trying ${CUSTOM_NODES_MANIFEST_URL}..."
  if ! install_custom_nodes; then
    echo "⚠️ install_custom_nodes reported errors; custom-node extras may be incomplete."
  fi
  snapshot_custom_nodes_state "after-install_custom_nodes" || true
else
  echo "INSTALL_CUSTOM_NODES=false → skipping extra custom node installation."
fi

aria2_show_download_snapshot || true

#------------------------------------------------------------------------
section 8 "Relevant/Needed Repo Files Pull and Symlink/Rsync"
#----------------------------------------------
# Optional Hearmeman workflows/assets sync
#----------------------------------------------

#----------------------------------------------
# Synchronize 'MyLoras' from HF to local cache repo (and symlink into ComfyUI)

#init_repo --hf "$HF_MYLORA_REPO_ID" "$HF_MYLORA_REPO_LOCAL" '*.safetensors' || true
#rsync_or_symlink_source_to_destination symlink "$HF_MYLORA_REPO_LOCAL" "$LORAS_DIR"

#----------------------------------------------
# Synchronize Hearmeman WAN git repo (and copy workflows into ComfyUI - merge with existing 'workflows' dir)

init_repo --git "$GIT_HEARMEMAN_WAN_REPO_ID" "$GIT_HEARMEMAN_WAN_REPO_LOCAL" || true
rsync_or_symlink_source_to_destination rsync "$GIT_HEARMEMAN_WAN_REPO_LOCAL/workflows/" \
                                             "$COMFY_HOME/user/default/"

#----------------------------------------------
# Synchronize My WAN git repo (and copy workflows into ComfyUI - repo_name subdir under 'workflows')

init_repo --git "$GIT_MYWORKFLOWS_REPO_ID" "$GIT_MYWORKFLOWS_REPO_LOCAL" || true
rsync_or_symlink_source_to_destination rsync "$GIT_MYWORKFLOWS_REPO_LOCAL/" \
                                             "$COMFY_HOME/user/default/workflows/"

#------------------------------------------------------------------------
section 9 "Aria2 (Manifest+CivitAI) Tracking"
#----------------------------------------------
# Wait for all downloads to complete
#----------------------------------------------

echo "[aria2-downloads-progress] Checking download progress..."

aria2_monitor_progress || true

aria2_clear_results >/dev/null 2>&1 || true

#------------------------------------------------------------------------
section 10 "Jupyter Launch"
#----------------------------------------------
# Optionally start Jupyter if requested
#----------------------------------------------

if [[ "${LAUNCH_JUPYTER:-false}" == "true" ]]; then
  echo "Launching Jupyter. Trying from port 8888..."
  jupyter-lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password='' --ServerApp.allow_origin='*' --ServerApp.allow_credentials=True --notebook-dir=/workspace &>/workspace/logs/jupyter.log &
else
  echo "LAUNCH_JUPYTER=0 → skipping Jupyter launch..."
fi

#------------------------------------------------------------------------
section 11 "Comfy Flow/Methodology Specific Configurations"
#----------------------------------------------
# Specific Hearmeman methodologies / setups
#-------------------------------------------

change_latent_preview_method || true

#------------------------------------------------------------------------
section 12 "ComfyUI Launch"
#----------------------------------------------
# Report the Custom Nodes being used for this 
#   session. Use tmux's to launch ComfyUI
#   Send telegram message if configured
#----------------------------------------------

# Final snapshot of custom_nodes before ComfyUI launch
snapshot_custom_nodes_state --summary "before-comfy-launch" || true

cd "${COMFY_HOME:-/workspace/ComfyUI}"

#----------------------------------------------
# Fix Numeric stack
#----------------------------------------------

fix_numeric_stack_if_broken


echo ""
echo "▶️  Starting ComfyUI"
echo ""

if ${SCRIPT_DIR}/run_comfy_mux.sh; then
  tg "🚀 ComfyUI is UP on 8188, 8288 (GPU0), 8388 (GPU1 if present)." || true
else
  tg "⚠️ ComfyUI launch had warnings. Check ${COMFY_LOGS}." || true
fi

echo ""
echo "Bootstrap complete. Bootstrap log: ${COMFY_LOGS}/startup.log"
echo "General logs: ${COMFY_LOGS}"
echo ""

echo "=== Bootstrap done: $(date) ==="

sleep infinity